New Funding Reference class
kbase/workspace_deluxe pull request #643
Opened 2022-11-08 18:10 UTC by ialarmedalien

Funding reference class:
- funderName: string, required
- funderID: string, PID format, optional
- awardID: string, may or may not be in PID format, optional
- awardTitle: string, optional
- awardURI: URL, optional

2022-11-08 19:16 UTC, ialarmedalien commented on src/us/kbase/workspace/test/database/provenance/FundingReferenceTest.java
> +					"It should match the pattern \"^([a-zA-Z0-9][a-zA-Z0-9\\.]+)\\s*:\\s*(\\S.+)$\""));
this test currently fails; it will pass once #639 is merged.

2022-11-11 23:22 UTC, MrCreosote requested changes
Looks good other than inconsistent names / returns for the URL/URI methods

2022-11-11 23:22 UTC, MrCreosote commented on src/us/kbase/workspace/database/provenance/FundingReference.java
> +	public Optional<URL> getAwardURI() {
Hmm, method says it's returning a URI but actually returns a URL

2022-11-14 18:38 UTC, MrCreosote approved these changes

2022-11-14 18:48 UTC, merged