CE-97: funding ref error collation
kbase/workspace_deluxe pull request #656
Opened 2022-12-20 21:21 UTC by ialarmedalien

Another bit of error collation fun with standard disclaimer about greater maintenance burden, etc.

2022-12-21 17:06 UTC, ialarmedalien commented on src/us/kbase/workspace/test/database/provenance/FundingReferenceTest.java
> +	private void assertFundingReferenceFields(FundingReference fr, final Map<String, String> expectedMap,
refactor the tests so that the passing tests all use this function to check that the output object is as expected

2022-12-21 17:07 UTC, ialarmedalien commented on src/us/kbase/workspace/test/database/provenance/FundingReferenceTest.java
> +	private void buildFundingRefFailWithError(final FundingReference.Builder builder, final String errorString) {
refactor again - function for checking error message for failing object construction

2022-12-22 00:41 UTC, MrCreosote commented on src/us/kbase/workspace/database/provenance/FundingReference.java
> +	 *                name of the funding body
readability++

2022-12-22 01:02 UTC, MrCreosote requested changes
A couple minor things + standard disapprobation clause

2022-12-22 14:42 UTC, ialarmedalien commented on src/us/kbase/workspace/database/provenance/FundingReference.java
> +			}
OK -- I will assess the situation once this PR and the next one are merged.

2022-12-22 18:01 UTC, MrCreosote approved these changes

2022-12-22 18:49 UTC, merged